Feature/soma
laryssa15s/calc-gqso-laryssa-924 pull request #5
Opened 2021-08-18 00:50 UTC by laryssa15s

se o parâmetro for uma letra o servidor retorna bad request

2021-09-07 21:48 UTC, Emanuelly03 requested changes
O código está funcional mas seria importante realizar a modificação sugerida

2021-09-07 21:48 UTC, Emanuelly03 commented on calc-api-924/src/main/java/app/Soma.java
> +           throw new BadRequestException(String.format("Contém parâmetro inválido"));
Seria interessante exibir qual parâmetro é inválido para facilitar a correção.

2021-09-14 21:25 UTC, laryssa15s commented on calc-api-924/src/main/java/app/Soma.java
> +           throw new BadRequestException(String.format("Contém parâmetro inválido"));
A alteração já foi executada.

2021-09-14 21:58 UTC, Emanuelly03 approved these changes

2021-09-14 22:00 UTC, merged